All
DmitriyV003/gokeeper pull request #1
Opened 2023-02-09 20:19 UTC by DmitriyV003

2023-02-14 20:27 UTC, kilchik requested changes

2023-02-14 20:27 UTC, kilchik commented on Makefile
> +proto:
Добавь пжлст README или команды в Makefile о том, как локально запускать клиент и сервер

2023-02-14 20:27 UTC, kilchik commented on cmd/cli/commands/create_login.go
> +package commands
Обычно в cmd располагается только точка входа в программу, я бы предложил commands вынести, например, в /internal/client

2023-02-14 20:27 UTC, kilchik commented on internal/config/config.go
> +	DBUri          string `envconfig:"DB_URI" default:"postgres://homestead:homestead@localhost:54321/homestead"`
Все-таки конфиги для сервера и клиента должны быть разными. Странно, что клиент при инициализации что-то знает про конфигурацию сервера на уровне кода

2023-02-14 20:27 UTC, kilchik commented on cmd/cli/main.go
> +	commands.Execute(ctx, deps)
cobra умеет обрабатывать сигналы ОС сама? Или здесь не хватает обработчика?

2023-02-14 20:27 UTC, kilchik commented on cmd/rsa-keys/main.go
> +func ExportPublicKeyAsPemStr(pubkey *rsa.PublicKey) string {
А где используется эта функция? Не увидел SSL для безопасной передачи данных между клиентом и сервером

2023-02-14 20:27 UTC, kilchik commented on internal/core/services/login_secret.go
> +	res, _ := l.client.CreateLoginSecret(ctx, &req)
Почему здесь игнорируется ошибка?

2023-02-14 20:27 UTC, kilchik commented on migrations/002_create_data_table.sql
>  CREATE TABLE IF NOT EXISTS credit_cards(
Миграции для credit_cards и notes нашел, а хэндлеров для них не нашел. По заданию требуется поддержать работу с несколькими типами данных

2023-02-14 20:27 UTC, kilchik commented on internal/server/login_secret_server.go
> +	id, _ := l.secretService.CreateLoginSecret(ctx, req)
Ошибка игнорируется, во всех хэндлерах должно быть реализовано подробное логирование

2023-02-20 11:16 UTC, dmitriyV25 commented on cmd/cli/main.go
> +	commands.Execute(ctx, deps)
немного не понимаю коммент. Приложение cli живет только в рамках одной команды

2023-02-20 11:53 UTC, dmitriyV25 commented
Антон, добрый день! Исправил недочеты, которые успел. Очень трудно совмещать с написанием диплома и работой.

2023-02-27 18:14 UTC, kilchik approved these changes

2023-02-28 07:28 UTC, merged